### PR TITLE
Added height of tree recurssive fn

### PR DESCRIPTION
**Pull request by shubhamc1200**

### CODE REVIEW

**Review by adarshvulli — CHANGES_REQUESTED** [review]
sir everything is good! can you please add the public to the class! it would be helpful for first-time users! because they are new

**Comment by shubhamc1200** [comment]
Yess!

**Comment by shubhamc1200** [comment]
So shall I make another PR?

**Comment by adarshvulli** [comment]
no! just comment on the changes in the existing file and push it! no need to make a new PR

**Comment by shubhamc1200** [comment]
Can you check is it done??

**Review by adarshvulli — APPROVED** [review]

**Comment by shubhamc1200** [comment]
I updated it

**Comment by shubhamc1200** [comment]
Thanks!

**Pull request merged**
