### PR TITLE
Added Monkey Sort to the Sorting Algorithms

### LINKED ISSUE #217: Adding a new sorting technique.
I wish to contribute to this repository by adding a new sorting algorithm in Python Programming Language.
It is known as Monkey sort.
I will provide all the necessary details on this technique also in my file, so users who don't have any information on it, might still be able to get an idea on this sorting technique.

Will be waiting for a response to go ahead :)

### PR DESCRIPTION
**Pull request by noviicee**
## Related Issuse
  -Adding a new sorting technique.
Closes: #[217]

#### Describe the changes you've made
Adding a new sorting algorithm in Python Programming Language.
It is known as Monkey sort.
All the necessary details on this technique is also in the md file, so users who don't have any information on it, might still be able to get an idea on this sorting technique.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

I have tested the codes on my local machine by running it on the terminal. Since it makes use of the random module, which generates new set on each  run, it is unnecessary to use doctest for this implementation.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by noviicee** [comment]
Is it okay..?

**Comment by noviicee** [comment]
Thank you!
Btw, there are several other searching and sorting techniques, which are implemented in other languages, but not in Python.
So can I add their implementations in Python as well?

**Comment by ankitapuri** [comment]
> Thank you!
> Btw, there are several other searching and sorting techniques, which are implemented in other languages, but not in Python.
> So can I add their implementations in Python as well?
Just join discord channel once for discussion : https://discord.gg/68MfEh6C

**Comment by noviicee** [comment]
> > Thank you!
> > Btw, there are several other searching and sorting techniques, which are implemented in other languages, but not in Python.
> > So can I add their implementations in Python as well?
> > Just join discord channel once for discussion : https://discord.gg/68MfEh6C

Thanks!

**Pull request merged**
