### PR TITLE
Added Resources, Nqueen and Dijkshatra algos

### PR DESCRIPTION
**Pull request by MananOO12**
Added Nqueen and Dijkshatra algos 
Added linear stack and linear queue implementation 
Updated README.md
Added a Reference folder containing various books 
Language Opted ?
C/C++

Number of files added or updated ?
7

Name of these files ?

dynamic_programming/C++/DIJKSTRA'S .cpp
dynamic_programming/C++/NQueen.cpp
dynamic_programming/C/NQueen.c
dynamic_programming/C/DIJKSTRA'S .c
Data_Structures_Implementation/Queue/queue.cpp
Data_Structures_Implementation/Stack/stack.c
Data_Structures_Implementation/Queue/queue1.c

### CODE REVIEW

**Comment by ankitapuri** [comment]
you have done stack and queue one previously as well.

**Comment by MananOO12** [comment]
> you have done stack and queue one previously as well.

Yes

**Comment by ankitapuri** [comment]
So why are adding them up again and asking for review

**Comment by MananOO12** [comment]
> So why are adding them up again and asking for review 

That was queue using linked list this is linear queue.
Also there are other programs.

**Review by ankitapuri — APPROVED** [review]

**Pull request merged**
