### PR TITLE
Issue Solved #183: Added Wave sort 

### LINKED ISSUE #183: Wave Sort
I will add Wave Sort using C++

### PR DESCRIPTION
**Pull request by ShudhanshuSingh**
## Wave Sort #183

Closes: #183

#### changes made
Created Wave Sort folder -> Added Wave Sort algorithm using C++ and its README.md file to explain algorithm

### CODE REVIEW

**Comment by ankitapuri** [comment]
Its not giving a sorted output

**Comment by ShudhanshuSingh** [comment]
> Its not giving a sorted output

image
I have tested this code on geeksforgeeks, it gives correct output

**Comment by rakesh0x7** [comment]
@ShudhanshuSingh I would like to suggest taking input from the user. it looks good when you take the user input.

**Comment by ankitapuri** [comment]
> > Its not giving a sorted output
> 
> image
> I have tested this code on geeksforgeeks, it gives correct output

Okay I will check it once again and take the input from the user .

**Pull request closed without merging**
