### PR TITLE
Added source code for Compare string by frequency of smallest character

### LINKED ISSUE #275: Compare the strings by frequency of the smallest character.
## 💥 Proposal

Let the function f(s) be the frequency of the lexicographically smallest character in a non-empty string s. For example, if s = "dcce" then f(s) = 2 because the lexicographically smallest character is 'c', which has a frequency of 2.

You are given an array of strings words and another array of query strings queries. For each query queries[i], count the number of words in words such that f(queries[i]) < f(W) for each W in words.

Return an integer array answer, where each answer[i] is the answer to the ith query.

### PR DESCRIPTION
**Pull request by abhinav5481**
## Related Issues
  - Compare string by frequency of smallest character

Closes: #275

#### Describe the changes you've made
I have written the source code for the given problem.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?
I have tested it on my Anaconda Powershell Prompt

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |
image

Please review my code & let me know if any changes are required.

### CODE REVIEW

**Comment by abhinav5481** [comment]
Hi @ankitapuri 
Please review my code.

**Review by ankitapuri — CHANGES_REQUESTED** [review]
Add comments along with your code

**Comment by abhinav5481** [comment]
Okay.

**Comment by abhinav5481** [comment]
Hi @ankitapuri 
I have added comments in my code. Please review & merge it.

**Review by ankitapuri — APPROVED** [review]

**Pull request merged**
