### PR TITLE
Added Merge Sort in Python and C++

### PR DESCRIPTION
**Pull request by Sahith02**
This is the code for merge sort in python and C++ with taking input from the user. Please review it and merge it if it's fine.

### CODE REVIEW

**Comment by ankitapuri** [comment]
@ADARSHULTIMATE please review it once

**Comment by Sahith02** [comment]
I've added Merge Sort in C++ as well now. Please review both the files.

**Review by ankitapuri — APPROVED** [review]

**Review by adarshvulli — CHANGES_REQUESTED** [review]
sir ! the python code has few errors please do the required changes

**Comment by Sahith02** [comment]
> sir ! the python code has few errors please do the required changes

Please ignore the above re-review. It was a mistake. When I tested it, it worked fine. Could you tell me what error?

**Review by adarshvulli — APPROVED** [review]

**Comment by adarshvulli** [comment]
@Sahith02 its a fault from my side! cool! good work!

**Pull request merged**
