### PR TITLE
Added Data Structures Implementation

### PR DESCRIPTION
**Pull request by MananOO12**
Thought of contributing some basic implementation of data structures.

### CODE REVIEW

**Comment by ankitapuri** [comment]
If you are adding all DS then also add Linked list please

**Comment by MananOO12** [comment]
> If you are adding all DS then also add Linked list please

It’s there under the name linkedlist.cpp

**Comment by ankitapuri** [comment]
> > If you are adding all DS then also add Linked list please
> 
> It’s there under the name linkedlist.cpp

you have deleted it actually

**Comment by MananOO12** [comment]
> > > If you are adding all DS then also add Linked list please
> > 
> > 
> > It’s there under the name linkedlist.cpp
> 
> you have deleted it actually

Actually I added two programs under different name so I removed one file. Should I add that also?

**Comment by MananOO12** [comment]
> > > If you are adding all DS then also add Linked list please
> > 
> > 
> > It’s there under the name linkedlist.cpp
> 
> you have deleted it actually

Check now

**Pull request closed without merging**
