### PR TITLE
Added Array Reversal

### PR DESCRIPTION
**Pull request by UG-SEP**
## Related Issuse
NA ,
There is no related issue

#### Describe the changes you've made
Only I have added Array reversal program in Arrays Folder.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

This is a hackerrank CP Website Question. Whose all test cases run successfully 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
|

### CODE REVIEW

**Comment by UG-SEP** [comment]
@ankitapuri  Please review it

**Comment by UG-SEP** [comment]
@ankitapuri please review this

**Comment by ankitapuri** [comment]
You didn't get yourself assigned to work on it . which is against the work-flow .

**Comment by UG-SEP** [comment]
ok

**Comment by UG-SEP** [comment]
then i am closing this PR and sending you an issue to work

**Pull request closed without merging**
