### PR TITLE
[feature-1] Added Find_pairs_with_given_sum. in CPP

### LINKED ISSUE #233: Find pair with given sum
## 💥 Proposal

(A clear and concise description of what the proposal is.)
The question is to find a pair that gives the sum that the user has entered. It can be implemented by sorting the array and using `Two Pointer` approach.

### Have you read the *Contributing Guidelines on Pull Requests* ?

(Write your answer here.)
YES

### PR DESCRIPTION
**Pull request by kiruba-r11**
## Related Issues
- Finding whether a pair with a given sum in the Array exists or not, implemented in CPP

Closes: #233 

#### Describe the changes you've made
I have completely implemented a CPP program that takes the input of array elements from the user and prints the **true** if a`Pair with given sum` exists else prints **false**

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

This has been tested by generating a set of random inputs using a generator and verified the outputs manually.

#### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by kiruba-r11** [comment]
@ankitapuri Please have a look at it

**Review by ankitapuri — CHANGES_REQUESTED** [review]
Its always printing pair not found .

**Comment by kiruba-r11** [comment]
@ankitapuri The problem works fine and I have tested it. I hope you would have entered the inputs in unsorted order, but the inputs for this question must be in sorted order to use the `Two Pointer` concept.

**Comment by ankitapuri** [comment]
image
see this

**Comment by kiruba-r11** [comment]
@ankitapuri It's correct, there are pairs with sum 5, that is 1,4 and 2,3. The question is to return true or false about whether a pair is found or not, and not to print the pair found.

**Pull request merged**
