### PR TITLE
added insertion_sort in python

### PR DESCRIPTION
**Pull request by tahmid02016**

### CODE REVIEW

**Review by ankitapuri — DISMISSED** [review]
write index instead of i

**Comment by tahmid02016** [comment]
I think i sutes the best. If I use index instead of i, then what about j.

**Comment by ankitapuri** [comment]
using i is outdated

**Comment by tahmid02016** [comment]
Okey. Please Checkout now.

**Comment by ankitapuri** [comment]
@ADARSHULTIMATE please review it once now

**Comment by SArikeshi** [comment]
There's no code for getting input.

**Comment by tahmid02016** [comment]
> There's no code for getting input.

I've added it. Please check now.

**Comment by adarshvulli** [comment]
@tahmid02016 sir! I request you to please check your code once again! there are few errors!

**Review by adarshvulli — APPROVED** [review]
cool

**Pull request merged**
