### PR TITLE
Created Heap_Sort.c

### PR DESCRIPTION
**Pull request by shiladityaroy212**
Created a new file to implement heap sort using C language. Please check the same. If you like the program, please accept the pull request.

**File name: Heap_sort.c
Destination : DSA-guide/Heap_Sort/Heap_sort.c**
Thank you

### CODE REVIEW

**Review by ankitapuri — CHANGES_REQUESTED** [review]
Your code is not working

**Comment by shiladityaroy212** [comment]
I am looking into the code again . Give me some time. Will give you by
today itself

**Comment by shiladityaroy212** [comment]
I have changed the heap sort code in C and updated it. It's working properly now. Please have a look to it. If you like it, please accept it.

Thank you.

**Comment by shiladityaroy212** [comment]
> Your code is not working

I have sent my updated code yesterday. please have a look to it.

**Comment by ankitapuri** [comment]
why are printing the heap array its not required !

**Comment by shiladityaroy212** [comment]
I have just kept it so that it so that the person can check whether the
output generated is correct or not. If you want I can remove it.
Shall I remove it?? Or keep it? Please say

>

**Comment by shiladityaroy212** [comment]
> why are printing the heap array its not required !

As you have said I have removed the printing of the heap array part of my heap sort code in C. I have made the necessary updates in my code. If any further changes , please say me ,otherwise please accept my pull request and merge it in your repository .

Thank you

**Review by ankitapuri — APPROVED** [review]

**Pull request merged**
