### PR TITLE
Sudoku Solver (Python) 

### LINKED ISSUE #225: Sudoku Solver
## 💥 Proposal

(A clear and concise description of what the proposal is.)

The proposal is about a hard problem of backtracking/ recursion named Sudoku solver.

### Have you read the *Contributing Guidelines on Pull Requests* ?

(Write your answer here.)

Yes

### PR DESCRIPTION
**Pull request by Akash20x**
## Related Issuse
 Sudoku Solver Leetcode Problem 

Closes: #225 

#### Describe the changes you've made
Added a solution for the leetcode problem Sudoku Solver in python 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

This problem is tested on Leetcode platform 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |

### CODE REVIEW

**Review by ankitapuri — CHANGES_REQUESTED** [review]
Your output is not as expected . check it once . It is printing unnecessary stuff.

**Comment by Akash20x** [comment]
OK i will check again and update it

**Comment by Akash20x** [comment]
Please now check my pull request

**Comment by ankitapuri** [comment]
> Please now check my pull request

image
Its showing this error in my local machine as well as online compiler

**Comment by Akash20x** [comment]
I changed the code and it works fine on online compiler also.
Please check it

**Comment by ankitapuri** [comment]
Just make the output look like a board , rest everything is fine 👍

**Comment by Akash20x** [comment]
Ok

**Comment by Akash20x** [comment]
Please merge my pull request

**Review by ankitapuri — APPROVED** [review]

**Pull request merged**
