### PR TITLE
Added dynamic programming

### PR DESCRIPTION
**Pull request by Sadakant**
hi,

i have added the program to find the nth  Fibonacci number using dynamic programming

thank you

### CODE REVIEW

**Review by adarshvulli — CHANGES_REQUESTED** [review]
you did a great job! it would be great! if you comment the code!

**Comment by Sadakant** [comment]
> you did a great job! it would be great! if you comment the code!

yeah, sure i am adding it right now

thanks

**Comment by Sadakant** [comment]
> you did a great job! it would be great! if you comment the code!

hi 
i have added the comments please review it
thank you

**Comment by ADARSHULTIMATE** [comment]
sir! can you explain the output! I could only get my entered number apart from the series

**Pull request merged**
