### PR TITLE
Adding HashMap, stack, Dynamic Programming Algo

### PR DESCRIPTION
**Pull request by MananOO12**
I have added linear implementation of stack , two types of hashmap ,Nqueen and DIJKSTRA'S algorithm 

Language Opted ?
C/C++

Number of files added or updated ?
17

Name of these files ?
Data_Structures/Linked_List/Singly_Linked_List/linked.cpp
Data_Structures/Linked_List/Singly_Linked_List/linkedlist.cpp
Data_Structures/Queues/cirqueue.cpp
Data_Structures/Queues/linkqueue.cpp
Data_Structures/Queues/queue1.c
Data_Structures_Implementation/Queue/queue.cpp
Data_Structures/Stacks/linkstack.cpp
Data_Structures_Implementation/Stack/stack.c
Data_Structures/Tree/Binary_Search_Tree/operationBST.cpp
HashMap/separatechaining.c
HashMap/openaddress.c
dynamic_programming/C++/DIJKSTRA'S .cpp
dynamic_programming/C++/NQueen.cpp
dynamic_programming/C/NQueen.c
Recursion/C/powerRecursion.c
dynamic_programming/C/DIJKSTRA'S .c
Data_Structures_Implementation/README.md.txt

### CODE REVIEW

**Comment by ankitapuri** [comment]
Just close the previous PR if you added it all together

**Comment by MananOO12** [comment]
> Just close the previous PR if you added it all together

Done

**Comment by ankitapuri** [comment]
Delete the suduko solver , selection sort in js and include hashmaps inside the data structure folder itself

**Comment by MananOO12** [comment]
> Delete the suduko solver , selection sort in js and include hashmaps inside the data structure folder itself

sudoku and selection sort part is not mine.
Should I delete them?

**Comment by ankitapuri** [comment]
why its showing in your files then ???
Let me look into it

**Comment by ankitapuri** [comment]
And change that hash map folder

**Comment by MananOO12** [comment]
> why its showing in your files then ???
> Let me look into it

I was also confused.

**Comment by ankitapuri** [comment]
> And change that hash map folder

Do this as well @MananOO12

**Comment by MananOO12** [comment]
> > And change that hash map folder
> 
> Do this as well @MananOO12

On it.

**Comment by MananOO12** [comment]
I was having issues committing to this pull request, so I created a new pull request and closing this one.

**Pull request closed without merging**
