### PR TITLE
Added randomized quick sort

### PR DESCRIPTION
**Pull request by Sadakant**
hi

i have added the randomized version of the quick sort, please review it

thanks

### CODE REVIEW

**Comment by ankitapuri** [comment]
Its great but I just need 1 code and its done :-)

**Comment by Sadakant** [comment]
> Its great but I just need 1 code and its done :-)

But it is a randomized quick sort which is different from normal quick sort. You will not be able to figure out the worst case time complexity in case of the randomized version. In case of normal quick sort worst case will be completely sorted array which is not that rare in today's world. So please review it, it's the different code

**Review by adarshvulli — CHANGES_REQUESTED** [review]
sir! change the name of the class you took for the object creation! rest is good!

**Comment by Sadakant** [comment]
> sir! change the name of the class you took for the object creation! rest is good!

Didn't quite get it what you are trying to say. In java class name containing the main method and filename has to be the same. So can you please elaborate your query ?

**Comment by adarshvulli** [comment]
once check line 3 and line 80!both the class names didn't match

**Comment by Sadakant** [comment]
> once check line 3 and line 80!both the class names didn't match

Yeah sorry got it, have done the required changes, please review it 

Thanks

**Review by adarshvulli — APPROVED** [review]

**Pull request merged**
